package frames;

import Model.GameMessages;
import Model.Knight;
import Model.KnightDAO;
import images.SeletorImagens;
import java.util.List;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class Choose extends javax.swing.JFrame {

    private List <Knight> results;
    private List <Knight> results2;
    private int numberOfEntries;
    private int currentEntryIndex;
    private Knight knight;
    private Knight knightRandom;
    private KnightDAO knightDAO;
    private KnightDAO knightDAO2;
    private Random number = new Random(); //gerador de aleatórios;
    private int random;
    private GameMessages gameMessages = new GameMessages(); //gerador de mensagens;
    private SeletorImagens imagem = new SeletorImagens();
    
    
    /**
     * Creates new form choose
     */
    public Choose() {
        initComponents();
          
        this.knightDAO = new KnightDAO();
        this.knightDAO2 = new KnightDAO();
        
        jlKnight.setIcon(imagem.determinaImagem(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlEscolha = new javax.swing.JLabel();
        jbDetalhes = new javax.swing.JButton();
        jbAceitar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlCharacterName = new javax.swing.JLabel();
        jcEscolha = new javax.swing.JComboBox();
        jlKnight = new javax.swing.JLabel();

        setResizable(false);

        jlEscolha.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jlEscolha.setText("Escolha seu Cavaleiro:");

        jbDetalhes.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jbDetalhes.setText("Detalhes");
        jbDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDetalhesActionPerformed(evt);
            }
        });

        jbAceitar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jbAceitar.setText("Iniciar Batalha");
        jbAceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceitarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel1.setText("Options:");

        jlCharacterName.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N

        jcEscolha.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jcEscolha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "selecione", "1", "2", "3", "4" }));
        jcEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcEscolhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlCharacterName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 155, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbAceitar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlEscolha, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jlKnight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcEscolha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlKnight, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jlCharacterName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbDetalhes)
                .addGap(18, 18, 18)
                .addComponent(jbAceitar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //botão de escolha ComboBox
    private void jcEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcEscolhaActionPerformed
        //número do índice da ComboBox determina o ID;
        results = knightDAO.getKnightById(jcEscolha.getSelectedIndex());
        randomGenerator();
        
        results2 = knightDAO2.getKnightById(random); //AI aleatório;
        numberOfEntries = results.size(); //o tamanho de results(int);
        
        //mostra imagem correspondente;
        jlKnight.setIcon(imagem.determinaImagem(jcEscolha.getSelectedIndex()));
        
        //configura o personagem com a opção escolhida na ComboBox;
        if(numberOfEntries != 0){
            currentEntryIndex = 0;
            knight = results.get(currentEntryIndex); //configurando escolha;
            
            knightRandom = results2.get(currentEntryIndex); //configurando AI;
            
            this.jlCharacterName.setText(""+knight.getNome()); //mostra o nome da opção escolhida;    
        }else{
            this.jlCharacterName.setText("");
            gameMessages.alerts(); //alerta de validez
        }
        
    }//GEN-LAST:event_jcEscolhaActionPerformed

    private void jbDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDetalhesActionPerformed
        if(numberOfEntries != 0){
            Details details = new Details(knight, jcEscolha.getSelectedIndex());
            details.setLocationRelativeTo(this);
            details.setVisible(true);
        }else
            gameMessages.alerts();
        
    }//GEN-LAST:event_jbDetalhesActionPerformed
    
    private void jbAceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceitarActionPerformed
        if(numberOfEntries != 0){       
            Battle battle = new Battle(knight, knightRandom, jcEscolha.getSelectedIndex(), random);
            battle.setLocationRelativeTo(this);
            battle.setVisible(true);
        }else
            gameMessages.alerts();
        
    }//GEN-LAST:event_jbAceitarActionPerformed
    
    //retorna um número de 1 a 4;
    public void randomGenerator(){
        do
           random = (number.nextInt(4)+1); 
        while(random == jcEscolha.getSelectedIndex());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbAceitar;
    private javax.swing.JButton jbDetalhes;
    private javax.swing.JComboBox jcEscolha;
    private javax.swing.JLabel jlCharacterName;
    private javax.swing.JLabel jlEscolha;
    private javax.swing.JLabel jlKnight;
    // End of variables declaration//GEN-END:variables
}
